### PR TITLE
Adapt platform library name to p8-platform

### PR DESCRIPTION
**Pull request by Montellese**

### CODE REVIEW

**Comment by Montellese** [comment]
@AchimTuran: ping, this (and 2 PVR addons) is blocking win32 jenkins slave from finally succeeding again.

**Comment by AchimTuran** [comment]
@Montellese 
According to your ping I guess you missed my message on Slack :-)
And my ping here https://github.com/kodi-adsp/adsp.biquad.filters/pull/8. That could happen cause of the Github spam wave :-b

 I already adapted to the p8-platform name change that's why I will close this PR.

I will squash the commits and create a new branch for asplib.

**Comment by Montellese** [comment]
I haven't been on slack in weeks and I don't get any notifications from it.

As long as this gets fixed I'm happy. Thanks.

**Comment by AchimTuran** [comment]
> I haven't been on slack in weeks and I don't get any notifications from it.

Sorry I didn't know that you roughly use Slack. Next time I will write an e-mail. :-b

**Pull request closed without merging**
