### PR TITLE
Add CI builds

### PR DESCRIPTION
**Pull request by AchimTuran**
This PR adds Windows, Linux and OS X CI builds with Travis CI and AppVeyor.

Furthermore it adds the latest dependencies.

### CODE REVIEW

**Comment by AchimTuran** [comment]
@wsnipex @Montellese @notspiff
Does someone of you know why our build system does not download the dependencies with 
`-DADDON_SRC_PREFIX="path"`?

When I build this add-on locally without that option. All necessary downloads will be processed and the  dependencies are built before the add-on build starts. But I can not use this for Travis CI or AppVeyor, because it doesn't use the latest add-on sources.

Can someone of you help me to fix this issue?

For the commands please see [.travis.yml](https://github.com/AchimTuran/adsp.biquad.filters/blob/ci-builds/.travis.yml#L68) or [appveyor.yml](https://github.com/AchimTuran/adsp.biquad.filters/blob/ci-builds/appveyor.yml#L74).

**Comment by wsnipex** [comment]
ADDON_SRC_PREFIX expects to find a repo in the given location. It's intended for local development so you can test changes without committing and pushing to github all the time.
Travis doesn't build, because it doesn't find your addon anywhere. 

Simply remove ADDON_SRC_PREFIX

**Comment by wsnipex** [comment]
scrap that, I've read the travis file wrongly.
From the looks of it the paths are wrong and ADDON_SRC_PREFIX should point to TRAVIS_BUILD_DIR?
If that is where your addon is checked out to.
And the cmake command must be triggered from kodi_src/project/cmake/addons

**Comment by AchimTuran** [comment]
Thanks @wsnipex for the quick response.

With Travis CI or other services it's different. They do the clone for you, which normally does our build system. That's why I tried to use `-DADDON_SRC_PREFIX="path"`.

It has the same behaviour when I try the build with that commands locally. Normally I edit the text files and add file://<path> for a dependency.

If you scroll down then you see that the add-on source code is found and `asplib` (see [appveyor](https://ci.appveyor.com/project/AchimTuran/adsp-biquad-filters/build/master-c6c1cc4-2016-02-07#L455) or [travis ci](https://travis-ci.org/kodi-adsp/adsp.biquad.filters/jobs/107621116#L522) is missing. So I guess it doesn't download the required depencies with `-DADDON_SRC_PREFIX="path"`.
Our [README](https://github.com/xbmc/xbmc/blob/master/project/cmake/addons/README) says
`
ADDON_SRC_PREFIX can be used to override the addon repository location.
    It must point to the locally available parent directory of the addon(s) to build
    <addon-id> will be appended to this path automatically
`
So I guess we need something similiar for depends. Is that right?

Furthermore the builds are working with that commands if they don't need external depencies. See [adsp.basic](https://github.com/kodi-adsp/adsp.basic), [adsp.freesurround](https://github.com/kodi-adsp/adsp.freesurround) or the [pvr add-ons](https://github.com/kodi-pvr).

**Comment by AchimTuran** [comment]
@wsnipex the fixes do not help :-(

At the weekend I will debug our buildsystem to locate the problem.

**Comment by Montellese** [comment]
It would be nice to get the `p8-platform` fix in independent of getting travis/appveyor to work because this is "blocking" our regular jenkins builds. `ADDON_SRC_PREFIX` shouldn't have any influence on dependencies but it's been a while since I looked into it.

**Comment by AchimTuran** [comment]
@Montellese 
I squashed the commits, which will make you happy ;-)

I will this now and try to fix the issue with the dependencies later, when my rework of adsp.template is finished.

**Pull request merged**
